INSERT INTO public.catalog_items (name, category, default_unit) VALUES
('onion', 'Vegetables', 'kg'),
('red onion', 'Vegetables', 'kg'),
('garlic', 'Vegetables', 'g'),
('ginger', 'Vegetables', 'g'),
('tomato', 'Vegetables', 'kg'),
('potato', 'Vegetables', 'kg'),
('sweet potato', 'Vegetables', 'kg'),
('carrot', 'Vegetables', 'kg'),
('cucumber', 'Vegetables', 'pcs'),
('bell pepper', 'Vegetables', 'pcs'),
('green chili', 'Vegetables', 'g'),
('spinach', 'Vegetables', 'g'),
('lettuce', 'Vegetables', 'pcs'),
('cabbage', 'Vegetables', 'pcs'),
('cauliflower', 'Vegetables', 'pcs'),
('broccoli', 'Vegetables', 'pcs'),
('eggplant', 'Vegetables', 'kg'),
('okra', 'Vegetables', 'kg'),
('green beans', 'Vegetables', 'kg'),
('mushroom', 'Vegetables', 'g'),
('apple', 'Fruits', 'kg'),
('banana', 'Fruits', 'pcs'),
('orange', 'Fruits', 'kg'),
('lemon', 'Fruits', 'pcs'),
('lime', 'Fruits', 'pcs'),
('mango', 'Fruits', 'pcs'),
('grapes', 'Fruits', 'kg'),
('strawberry', 'Fruits', 'g'),
('blueberry', 'Fruits', 'g'),
('pineapple', 'Fruits', 'pcs'),
('watermelon', 'Fruits', 'pcs'),
('peach', 'Fruits', 'kg'),
('pear', 'Fruits', 'kg'),
('avocado', 'Fruits', 'pcs'),
('dates', 'Fruits', 'g'),
('raisins', 'Fruits', 'g'),
('pomegranate', 'Fruits', 'pcs'),
('coconut', 'Fruits', 'pcs'),
('chicken breast', 'Meat & Poultry', 'kg'),
('chicken thighs', 'Meat & Poultry', 'kg'),
('whole chicken', 'Meat & Poultry', 'kg'),
('ground beef', 'Meat & Poultry', 'kg'),
('beef steak', 'Meat & Poultry', 'kg'),
('lamb chops', 'Meat & Poultry', 'kg'),
('ground lamb', 'Meat & Poultry', 'kg'),
('turkey mince', 'Meat & Poultry', 'kg'),
('beef cubes', 'Meat & Poultry', 'kg'),
('mutton', 'Meat & Poultry', 'kg'),
('chicken sausage', 'Meat & Poultry', 'pack'),
('beef sausage', 'Meat & Poultry', 'pack'),
('salmon fillet', 'Seafood', 'kg'),
('white fish fillet', 'Seafood', 'kg'),
('tuna steak', 'Seafood', 'kg'),
('shrimp', 'Seafood', 'kg'),
('prawns', 'Seafood', 'kg'),
('cod', 'Seafood', 'kg'),
('tilapia', 'Seafood', 'kg'),
('sardines', 'Seafood', 'pack'),
('canned tuna', 'Seafood', 'pack'),
('crab meat', 'Seafood', 'g'),
('milk', 'Dairy & Eggs', 'l'),
('whole milk', 'Dairy & Eggs', 'l'),
('yogurt', 'Dairy & Eggs', 'g'),
('greek yogurt', 'Dairy & Eggs', 'g'),
('butter', 'Dairy & Eggs', 'g'),
('cheddar cheese', 'Dairy & Eggs', 'g'),
('mozzarella cheese', 'Dairy & Eggs', 'g'),
('cream cheese', 'Dairy & Eggs', 'g'),
('paneer', 'Dairy & Eggs', 'g'),
('eggs', 'Dairy & Eggs', 'pcs'),
('heavy cream', 'Dairy & Eggs', 'ml'),
('sour cream', 'Dairy & Eggs', 'g'),
('feta cheese', 'Dairy & Eggs', 'g'),
('condensed milk', 'Dairy & Eggs', 'ml'),
('basmati rice', 'Grains & Pulses', 'kg'),
('jasmine rice', 'Grains & Pulses', 'kg'),
('brown rice', 'Grains & Pulses', 'kg'),
('white rice', 'Grains & Pulses', 'kg'),
('quinoa', 'Grains & Pulses', 'g'),
('oats', 'Grains & Pulses', 'g'),
('wheat flour', 'Grains & Pulses', 'kg'),
('all purpose flour', 'Grains & Pulses', 'kg'),
('semolina', 'Grains & Pulses', 'g'),
('couscous', 'Grains & Pulses', 'g'),
('bulgur wheat', 'Grains & Pulses', 'g'),
('pasta', 'Grains & Pulses', 'pack'),
('spaghetti', 'Grains & Pulses', 'pack'),
('noodles', 'Grains & Pulses', 'pack'),
('chickpeas', 'Grains & Pulses', 'g'),
('red lentils', 'Grains & Pulses', 'g'),
('green lentils', 'Grains & Pulses', 'g'),
('black lentils', 'Grains & Pulses', 'g'),
('kidney beans', 'Grains & Pulses', 'g'),
('black beans', 'Grains & Pulses', 'g'),
('mung beans', 'Grains & Pulses', 'g'),
('split peas', 'Grains & Pulses', 'g'),
('pearl barley', 'Grains & Pulses', 'g'),
('cornmeal', 'Grains & Pulses', 'g'),
('salt', 'Spices & Seasonings', 'g'),
('black pepper', 'Spices & Seasonings', 'g'),
('red chili powder', 'Spices & Seasonings', 'g'),
('paprika', 'Spices & Seasonings', 'g'),
('turmeric powder', 'Spices & Seasonings', 'g'),
('cumin seeds', 'Spices & Seasonings', 'g'),
('cumin powder', 'Spices & Seasonings', 'g'),
('coriander powder', 'Spices & Seasonings', 'g'),
('garam masala', 'Spices & Seasonings', 'g'),
('cinnamon', 'Spices & Seasonings', 'g'),
('cardamom', 'Spices & Seasonings', 'g'),
('cloves', 'Spices & Seasonings', 'g'),
('bay leaves', 'Spices & Seasonings', 'g'),
('oregano', 'Spices & Seasonings', 'g'),
('basil', 'Spices & Seasonings', 'g'),
('thyme', 'Spices & Seasonings', 'g'),
('rosemary', 'Spices & Seasonings', 'g'),
('parsley', 'Spices & Seasonings', 'g'),
('cilantro', 'Spices & Seasonings', 'g'),
('mint', 'Spices & Seasonings', 'g'),
('mustard seeds', 'Spices & Seasonings', 'g'),
('fenugreek seeds', 'Spices & Seasonings', 'g'),
('saffron', 'Spices & Seasonings', 'g'),
('curry leaves', 'Spices & Seasonings', 'g'),
('italian seasoning', 'Spices & Seasonings', 'g'),
('olive oil', 'Oils & Condiments', 'ml'),
('vegetable oil', 'Oils & Condiments', 'ml'),
('canola oil', 'Oils & Condiments', 'ml'),
('coconut oil', 'Oils & Condiments', 'ml'),
('ghee', 'Oils & Condiments', 'g'),
('sesame oil', 'Oils & Condiments', 'ml'),
('soy sauce', 'Oils & Condiments', 'ml'),
('vinegar', 'Oils & Condiments', 'ml'),
('apple cider vinegar', 'Oils & Condiments', 'ml'),
('ketchup', 'Oils & Condiments', 'ml'),
('mayonnaise', 'Oils & Condiments', 'g'),
('mustard sauce', 'Oils & Condiments', 'g'),
('hot sauce', 'Oils & Condiments', 'ml'),
('chili garlic sauce', 'Oils & Condiments', 'ml'),
('tamarind paste', 'Oils & Condiments', 'g'),
('tomato paste', 'Oils & Condiments', 'g'),
('peanut butter', 'Oils & Condiments', 'g'),
('bread', 'Bakery', 'pack'),
('whole wheat bread', 'Bakery', 'pack'),
('naan', 'Bakery', 'pack'),
('pita bread', 'Bakery', 'pack'),
('tortilla', 'Bakery', 'pack'),
('burger buns', 'Bakery', 'pack'),
('croissant', 'Bakery', 'pcs'),
('bagel', 'Bakery', 'pcs'),
('pizza base', 'Bakery', 'pack'),
('breadcrumbs', 'Bakery', 'g'),
('water', 'Beverages', 'l'),
('sparkling water', 'Beverages', 'l'),
('orange juice', 'Beverages', 'l'),
('apple juice', 'Beverages', 'l'),
('tea bags', 'Beverages', 'pack'),
('green tea', 'Beverages', 'pack'),
('coffee', 'Beverages', 'g'),
('instant coffee', 'Beverages', 'g'),
('cocoa powder', 'Beverages', 'g'),
('coconut water', 'Beverages', 'l'),
('almond milk', 'Beverages', 'l'),
('soda', 'Beverages', 'l'),
('sugar', 'Baking & Pantry', 'kg'),
('brown sugar', 'Baking & Pantry', 'kg'),
('powdered sugar', 'Baking & Pantry', 'g'),
('honey', 'Baking & Pantry', 'g'),
('maple syrup', 'Baking & Pantry', 'ml'),
('baking powder', 'Baking & Pantry', 'g'),
('baking soda', 'Baking & Pantry', 'g'),
('yeast', 'Baking & Pantry', 'g'),
('cornstarch', 'Baking & Pantry', 'g'),
('vanilla extract', 'Baking & Pantry', 'ml'),
('chocolate chips', 'Baking & Pantry', 'g'),
('cocoa nibs', 'Baking & Pantry', 'g'),
('canned tomatoes', 'Baking & Pantry', 'pack'),
('coconut milk', 'Baking & Pantry', 'ml'),
('stock cubes', 'Baking & Pantry', 'pack'),
('canned beans', 'Baking & Pantry', 'pack'),
('almonds', 'Baking & Pantry', 'g'),
('walnuts', 'Baking & Pantry', 'g')
ON CONFLICT (name) DO UPDATE SET category = excluded.category, default_unit = excluded.default_unit;
